export const genreList = [
    {
        id: 28,
        genre: "Action",
        icon: "faGun",
    }, {
        id: 12,
        genre: "Adventure",
        icon: "faMapLocationDot",
    }, {
        id: 16,
        genre: "Animation",
        icon: "faRobot",
    }, {
        id: 35,
        genre: "Comedy",
        icon: "faLaugh",
    }, {
        id: 80,
        genre: "Crime",
        icon: "faSkullCrossbones",
    }, {
        id: 99,
        genre: "Documentary",
        icon: "faClapperboard",
    }, {
        id: 18,
        genre: "Drama",
        icon: "faMasksTheater",
    }, {
        id: 10751,
        genre: "Family",
        icon: "faPeopleRoof",
    }, {
        id: 14,
        genre: "Fantasy",
        icon: "faFortAwesomeAlt",
    }, {
        id: 36,
        genre: "History",
        icon: "faShieldHalved",
    }, {
        id: 27,
        genre: "Horror",
        icon: "faGhost",
    }, {
        id: 10402,
        genre: "Music",
        icon: "faMusic",
    }, {
        id: 9648,
        genre: "Mystery",
        icon: "faSearchengin",
    }, {
        id: 10749,
        genre: "Romance",
        icon: "faHeartPulse",
    }, {
        id: 878,
        genre: "Sci-fi",
        icon: "faRocket",
    }, {
        id: 10770,
        genre: "TV Movie",
        icon: "faTv",
        isSelected: true
    }, {
        id: 53,
        genre: "Thriller",
        icon: "faPersonDigging",
    }, {
        id: 10752,
        genre: "War",
        icon: "faJetFighterUp",
    }, {
        id: 37,
        genre: "Western",
        icon: "faHatCowboy",
    }
]